local M = {}

function M.setup(colors, _, highlights)
  local apply = highlights.apply
  local link = highlights.link
  local apply_many = highlights.apply_many

  apply("DiffAdd", { fg = colors.light_green })
  apply("DiffChange", { fg = colors.cyan })
  apply("DiffDelete", { bold = true, fg = colors.red })
  apply("DiffText", { bold = true, bg = colors.red, fg = colors.white })
  link({ "diffAdded" }, "DiffAdd")
  link({ "diffRemoved" }, "DiffDelete")
  link({ "MiniDiffSignAdd", "MiniDiffOverAdd" }, "DiffAdd")
  link({ "MiniDiffSignDelete", "MiniDiffOverDelete" }, "DiffDelete")
  link({ "MiniDiffSignChange", "MiniDiffOverChange" }, "DiffChange")
  apply("MiniDiffOverContext", { bg = colors.purple })
  apply("IndentLine", { fg = "#767676" })
  apply("IndentBlanklineSpaceChar", { nocombine = true, fg = "#767676" })
  apply("IndentBlanklineContextStart", { underline = true, sp = colors.dark_brown })
  link({ "IndentBlanklineSpaceCharBlankline", "IndentBlanklineChar" }, "IndentBlanklineSpaceChar")
  apply("IndentBlanklineContextChar", { nocombine = true, fg = colors.dark_brown })
  apply("TelescopeBorder", { fg = colors.light_brown })
  apply("TelescopeSelection", { fg = colors.dark_orange })
  apply("TelescopeTitle", { fg = colors.red })
  link({ "TelescopePromptTitle" }, "TelescopeTitle")
  apply("TelescopePromptNormal", { fg = colors.yellow })
  link({ "TelescopePromptPrefix", "TelescopeMatching" }, "TelescopePromptNormal")
  link({ "zshDeref" }, "Constant")

  -- Completion
  link({ "CmpItemAbbr", "BlinkCmpLabel" }, "Normal")
  link({ "CmpItemAbbrDeprecated", "BlinkCmpLabelDeprecated" }, "Comment")
  apply_many({ "CmpItemAbbrMatch", "CmpItemAbbrMatchFuzzy", "BlinkCmpLabelMatch" }, { bold = true, fg = colors.yellow })
  link({ "CmpItemKind", "BlinkCmpKind" }, "Function")
  link({ "CmpItemMenu", "BlinkCmpSource" }, "Comment")
  link({ "BlinkCmpMenu", "BlinkCmpDoc", "BlinkCmpSignatureHelp" }, "NormalFloat")
  link({ "BlinkCmpMenuBorder", "BlinkCmpDocBorder", "BlinkCmpSignatureHelpBorder" }, "TelescopeBorder")
  link({ "BlinkCmpMenuSelection" }, "PmenuSel")
  link({ "BlinkCmpDocSeparator" }, "WinSeparator")
  link({ "BlinkCmpSignatureHelpActiveParameter" }, "Search")

  -- Git and file explorers
  link({ "GitSignsAdd", "GitSignsAddNr", "GitSignsAddLn" }, "DiffAdd")
  link({ "GitSignsChange", "GitSignsChangeNr", "GitSignsChangeLn" }, "DiffChange")
  link({ "GitSignsDelete", "GitSignsDeleteNr", "GitSignsDeleteLn" }, "DiffDelete")
  link({ "NeoTreeNormal", "NeoTreeNormalNC", "OilNormal" }, "Normal")
  link({ "NeoTreeDirectoryName", "NeoTreeDirectoryIcon", "OilDir", "OilDirIcon" }, "Directory")
  link({ "NeoTreeRootName" }, "Title")
  link({ "NeoTreeGitAdded" }, "DiffAdd")
  link({ "NeoTreeGitModified" }, "DiffChange")
  link({ "NeoTreeGitDeleted" }, "DiffDelete")
  link({ "OilLink" }, "Underlined")
  link({ "OilCopy", "OilMove", "OilCreate" }, "DiffAdd")
  link({ "OilDelete" }, "DiffDelete")
  link({ "OilPermission", "OilSize", "OilMTime" }, "Comment")

  -- UI plugins
  link({ "WhichKey", "WhichKeyGroup" }, "Function")
  link({ "WhichKeyDesc" }, "Normal")
  link({ "WhichKeySeparator", "WhichKeyValue" }, "Comment")
  link({ "WhichKeyFloat" }, "NormalFloat")
  link({ "WhichKeyBorder" }, "TelescopeBorder")
  link({ "LazyNormal" }, "NormalFloat")
  link({ "LazyButton" }, "Pmenu")
  link({ "LazyButtonActive" }, "PmenuSel")
  link({ "LazyH1" }, "Title")
  link({ "LazyComment" }, "Comment")
  link({ "LazyReasonPlugin" }, "Function")
  link({ "LazyValue" }, "String")
  link({ "NoiceCmdline", "NoicePopup", "NoiceConfirm" }, "NormalFloat")
  link({ "NoiceCmdlinePopup", "NoicePopupmenu" }, "Pmenu")
  link({ "NoiceCmdlinePopupBorder", "NoicePopupBorder", "NoiceConfirmBorder" }, "TelescopeBorder")
  link({ "NoiceCmdlineIcon", "NoiceFormatEvent", "NoiceFormatKind" }, "Special")
  link({ "NoiceFormatTitle" }, "Title")
  link({ "NoiceFormatDate" }, "Comment")
  link({ "NoiceFormatProgressDone" }, "DiffAdd")
  link({ "NoiceFormatProgressTodo" }, "Comment")
  link({ "SnacksDashboardNormal" }, "Normal")
  link({ "SnacksDashboardHeader", "SnacksDashboardIcon", "SnacksDashboardSpecial" }, "Title")
  link({ "SnacksDashboardDesc", "SnacksDashboardFooter" }, "Comment")
  link({ "SnacksDashboardKey" }, "Function")
  link({ "SnacksPicker", "SnacksPickerList", "SnacksPickerInput" }, "NormalFloat")
  link({ "SnacksPickerBorder" }, "TelescopeBorder")
  link({ "SnacksPickerTitle" }, "Title")
  link({ "SnacksPickerListCursorLine" }, "PmenuSel")
  link({ "SnacksPickerMatch" }, "Search")
  link({ "SnacksPickerDir" }, "Directory")
  link({ "SnacksPickerGitStatusAdded" }, "DiffAdd")
  link({ "SnacksPickerGitStatusModified" }, "DiffChange")
  link({ "SnacksPickerGitStatusDeleted" }, "DiffDelete")
  link({ "SnacksIndent" }, "IblIndent")
  link({ "SnacksIndentScope" }, "IblScope")
  link({ "MiniStarterCurrent", "MiniStarterItem" }, "Normal")
  link({ "MiniStarterFooter" }, "Comment")
  link({ "MiniStarterHeader" }, "Title")
  link({ "MiniStarterItemBullet", "MiniStarterQuery" }, "Special")
  link({ "MiniStarterItemPrefix" }, "Function")
  link({ "MiniFilesNormal" }, "NormalFloat")
  link({ "MiniFilesBorder" }, "TelescopeBorder")
  link({ "MiniFilesTitle" }, "Title")
  link({ "MiniFilesDirectory" }, "Directory")
  link({ "MiniFilesFile" }, "Normal")
  link({ "MiniPickNormal" }, "NormalFloat")
  link({ "MiniPickBorder", "MiniPickBorderBusy" }, "TelescopeBorder")
  link({ "MiniPickHeader" }, "Title")
  link({ "MiniPickMatchCurrent" }, "PmenuSel")
  link({ "MiniPickMatchMarked", "MiniPickMatchRanges" }, "Search")
  link({ "MiniPickPrompt" }, "Function")
  link({ "MiniIndentscopeSymbol" }, "IblScope")
  link({ "MiniJump", "MiniJump2dSpot" }, "Search")
  link({ "TroubleNormal", "TroubleNormalNC" }, "Normal")
  link({ "TroubleText", "TroubleFile" }, "Normal")
  link({ "TroubleCount" }, "PmenuSel")
  link({ "TroubleIndent" }, "IblIndent")
  link({ "TroubleFoldIcon" }, "Special")
  link({ "TroubleSource" }, "Comment")
  link({ "TroubleCode" }, "Number")
  link({ "TroubleLocation" }, "Function")
  link({ "TroubleSignError", "TroubleError" }, "DiagnosticError")
  link({ "TroubleSignWarning", "TroubleWarning" }, "DiagnosticWarn")
  link({ "TroubleSignInformation", "TroubleInformation" }, "DiagnosticInfo")
  link({ "TroubleSignHint", "TroubleHint" }, "DiagnosticHint")
  link({ "NotifyERRORIcon", "NotifyERRORTitle", "NotifyERRORBorder" }, "DiagnosticError")
  link({ "NotifyWARNIcon", "NotifyWARNTitle", "NotifyWARNBorder" }, "DiagnosticWarn")
  link({ "NotifyINFOIcon", "NotifyINFOTitle", "NotifyINFOBorder" }, "DiagnosticInfo")
  link({ "NotifyDEBUGIcon", "NotifyDEBUGTitle", "NotifyDEBUGBorder" }, "DiagnosticHint")
  link({ "NotifyTRACEIcon", "NotifyTRACETitle", "NotifyTRACEBorder" }, "Comment")
  link({ "NotifyERRORBody", "NotifyWARNBody", "NotifyINFOBody", "NotifyDEBUGBody", "NotifyTRACEBody" }, "NormalFloat")
  link({ "NotifyBackground" }, "NormalFloat")
  link({ "BufferLineFill", "BufferLineBackground", "BufferLineBuffer" }, "TabLine")
  link({ "BufferLineBufferVisible", "BufferLineTab" }, "Normal")
  link({ "BufferLineBufferSelected", "BufferLineTabSelected" }, "TabLineSel")
  link({ "BufferLineCloseButton", "BufferLineCloseButtonVisible", "BufferLineModified" }, "Comment")
  link({ "BufferLineCloseButtonSelected", "BufferLineModifiedSelected" }, "TabLineSel")
  link({ "BufferLineSeparator", "BufferLineSeparatorVisible", "BufferLineDuplicate" }, "TabLine")
  link({ "BufferLineSeparatorSelected", "BufferLineIndicatorSelected" }, "TabLineSel")
  link({ "BufferLineError", "BufferLineErrorDiagnostic" }, "DiagnosticError")
  link({ "DressingInputNormal", "DressingSelectNormal" }, "NormalFloat")
  link({ "DressingInputBorder", "DressingSelectBorder" }, "TelescopeBorder")
  link({ "DressingInputTitle", "DressingSelectTitle" }, "Title")
  link({ "DapUIBreakpointsCurrentLine", "DapUIStoppedThread" }, "Search")
  link({ "DapUIBreakpointsDisabledLine", "DapUIWatchesEmpty" }, "Comment")
  link({ "DapUIBreakpointsInfo", "DapUIThread" }, "DiagnosticInfo")
  link({ "DapUIBreakpointsLine", "DapUILineNumber" }, "Number")
  link({ "DapUIBreakpointsPath", "DapUISource" }, "Directory")
  link({ "DapUIDecoration", "DapUIPlayPause", "DapUIRestart" }, "Special")
  link({ "DapUIFrameName", "DapUIVariable", "DapUIWatchesValue" }, "Normal")
  link({ "DapUIModifiedValue" }, "DiffChange")
  link({ "DapUIScope", "DapUIType" }, "Type")
  link({ "DapUIValue" }, "String")
  link({ "DapUIWinSelect" }, "PmenuSel")
  link({ "DiffviewDiffAdd", "DiffviewStatusAdded", "DiffviewFilePanelInsertions" }, "DiffAdd")
  link({ "DiffviewDiffChange", "DiffviewStatusModified" }, "DiffChange")
  link({ "DiffviewDiffDelete", "DiffviewStatusDeleted", "DiffviewFilePanelDeletions" }, "DiffDelete")
  link({ "DiffviewStatusRenamed", "DiffviewStatusUntracked" }, "Directory")
  link({ "DiffviewFilePanelTitle", "DiffviewPrimary" }, "Title")
  link({ "DiffviewSecondary" }, "Comment")
  link({ "FugitiveHeader", "fugitiveHeader" }, "Title")
  link({ "FugitiveHash", "fugitiveHash" }, "Number")
  link({ "FugitiveSymbolicRef", "fugitiveSymbolicRef" }, "Function")
  link({ "FugitiveUntracked", "fugitiveUntracked" }, "Directory")
  link({ "FugitiveUnstagedModification", "fugitiveUnstagedModification" }, "DiffChange")
  link({ "FugitiveStagedModification", "fugitiveStagedModification" }, "DiffAdd")
  link({ "NavicText", "NavicSeparator" }, "Normal")
  link({ "NavicIconsFile", "NavicIconsModule", "NavicIconsNamespace", "NavicIconsPackage" }, "Directory")
  link({ "NavicIconsClass", "NavicIconsInterface", "NavicIconsStruct", "NavicIconsTypeParameter" }, "Type")
  link({ "NavicIconsMethod", "NavicIconsFunction", "NavicIconsConstructor" }, "Function")
  link({ "NavicIconsProperty", "NavicIconsField", "NavicIconsVariable", "NavicIconsKey" }, "Identifier")
  link({ "NavicIconsEnum", "NavicIconsEnumMember", "NavicIconsConstant" }, "Constant")
  link({ "NavicIconsString" }, "String")
  link({ "NavicIconsNumber" }, "Number")
  link({ "NavicIconsBoolean" }, "Boolean")
  link({ "NavicIconsArray", "NavicIconsObject" }, "Special")
  link({ "NavicIconsEvent", "NavicIconsOperator" }, "Operator")
  link({ "NavicIconsNull" }, "Comment")
  link({ "DropBarIconKindFile", "DropBarIconKindFolder", "DropBarKindFile", "DropBarKindFolder" }, "Directory")
  link({ "DropBarIconKindClass", "DropBarKindClass", "DropBarIconKindInterface", "DropBarKindInterface" }, "Type")
  link({ "DropBarIconKindFunction", "DropBarKindFunction", "DropBarIconKindMethod", "DropBarKindMethod" }, "Function")
  link({ "DropBarMenuCurrentContext", "DropBarMenuHoverEntry" }, "PmenuSel")
  link({ "DropBarMenuHoverIcon", "DropBarMenuHoverSymbol" }, "Function")
  link({ "DropBarMenuSbar" }, "Pmenu")
  link({ "DropBarMenuThumb" }, "PmenuThumb")
  link({ "TreesitterContext" }, "NormalFloat")
  link({ "TreesitterContextLineNumber" }, "LineNr")
  link({ "TreesitterContextSeparator" }, "WinSeparator")
  link({ "RainbowDelimiterRed" }, "DiagnosticError")
  link({ "RainbowDelimiterYellow" }, "Search")
  link({ "RainbowDelimiterBlue" }, "DiagnosticInfo")
  link({ "RainbowDelimiterOrange" }, "Keyword")
  link({ "RainbowDelimiterGreen" }, "String")
  link({ "RainbowDelimiterViolet" }, "Label")
  link({ "RainbowDelimiterCyan" }, "DiffChange")
  link({ "AerialLine" }, "PmenuSel")
  link({ "AerialGuide" }, "IblIndent")
  link({ "AerialArray", "AerialObject", "AerialKey" }, "Special")
  link({ "AerialBoolean" }, "Boolean")
  link({ "AerialClass", "AerialInterface", "AerialStruct", "AerialTypeParameter" }, "Type")
  link({ "AerialConstant", "AerialEnum", "AerialEnumMember" }, "Constant")
  link({ "AerialConstructor", "AerialFunction", "AerialMethod" }, "Function")
  link({ "AerialField", "AerialProperty", "AerialVariable" }, "Identifier")
  link({ "AerialFile", "AerialModule", "AerialNamespace", "AerialPackage" }, "Directory")
  link({ "AerialNumber" }, "Number")
  link({ "AerialString" }, "String")
  link({ "OutlineCurrent" }, "PmenuSel")
  link({ "OutlineFoldMarker" }, "Special")
  link({ "OutlineGuides" }, "IblIndent")
  link({ "OutlineDetails" }, "Comment")
  link({ "OutlineNormal" }, "NormalFloat")
  link({ "OutlineWindowBorder" }, "TelescopeBorder")
  link({ "OutlineWindowTitle" }, "Title")
  link({ "NeogitBranch", "NeogitRemote" }, "Function")
  link({ "NeogitHunkHeader" }, "Pmenu")
  link({ "NeogitHunkHeaderHighlight" }, "PmenuSel")
  link({ "NeogitDiffContext" }, "Normal")
  link({ "NeogitDiffContextHighlight" }, "Visual")
  link({ "NeogitDiffAdd", "NeogitChangeAdded" }, "DiffAdd")
  link({ "NeogitDiffAddHighlight" }, "DiffAdd")
  link({ "NeogitDiffDelete", "NeogitChangeDeleted" }, "DiffDelete")
  link({ "NeogitDiffDeleteHighlight" }, "DiffDelete")
  link({ "NeogitChangeModified" }, "DiffChange")
  link({ "NeogitFilePath" }, "Directory")
  link({ "NeotestAdapterName", "NeotestNamespace" }, "Title")
  link({ "NeotestDir", "NeotestFile" }, "Directory")
  link({ "NeotestFocused", "NeotestMarked" }, "PmenuSel")
  link({ "NeotestIndent" }, "IblIndent")
  link({ "NeotestRunning" }, "DiagnosticInfo")
  link({ "NeotestWinSelect" }, "Search")
  link({ "NeotestPassed" }, "DiffAdd")
  link({ "NeotestFailed" }, "DiagnosticError")
  link({ "NeotestSkipped", "NeotestUnknown" }, "Comment")
  link({ "FzfLuaNormal" }, "NormalFloat")
  link({ "FzfLuaBorder" }, "TelescopeBorder")
  link({ "FzfLuaTitle", "FzfLuaHeaderText" }, "Title")
  link({ "FzfLuaCursor", "FzfLuaCursorLine" }, "PmenuSel")
  link({ "FzfLuaSearch", "FzfLuaFzfMatch" }, "Search")
  link({ "FzfLuaFzfMarker", "FzfLuaFzfPrompt" }, "Function")
  link({ "FzfLuaPathColNr", "FzfLuaPathLineNr", "FzfLuaBufNr" }, "Number")
  link({ "FzfLuaBufName" }, "Normal")
  link({ "FzfLuaHeaderBind", "FzfLuaLiveSym" }, "Comment")
  link({ "FzfLuaTabTitle" }, "Title")
  link({ "FzfLuaTabMarker" }, "Special")

  -- Indentation and rendered Markdown
  apply("IblIndent", { fg = "#767676" })
  link({ "IblWhitespace" }, "IblIndent")
  apply("IblScope", { fg = colors.dark_brown })
  link({ "IblScopeChar" }, "IblScope")
  apply_many({
    "RenderMarkdownH1",
    "RenderMarkdownH2",
    "RenderMarkdownH3",
    "RenderMarkdownH4",
    "RenderMarkdownH5",
    "RenderMarkdownH6",
  }, { bold = true, fg = colors.white })
  link({ "RenderMarkdownCode", "RenderMarkdownCodeInline" }, "Pmenu")
  link({ "RenderMarkdownBullet", "RenderMarkdownDash" }, "Special")
  link({ "RenderMarkdownQuote" }, "Comment")
  link({ "RenderMarkdownTableHead" }, "Title")
  link({ "RenderMarkdownTableRow" }, "Normal")
  link({ "RenderMarkdownLink" }, "Underlined")
end

return M
