local M = {}

local function apply(name, options)
  vim.api.nvim_set_hl(0, name, options)
end

local function link(names, target)
  for _, name in ipairs(names) do
    apply(name, { link = target })
  end
end

local function apply_many(names, options)
  for _, name in ipairs(names) do
    apply(name, options)
  end
end

function M.setup()
  local colors = require("railscasts.colors")
  local options = require("railscasts.config").get()
  local background = options.transparent and "NONE" or colors.background

  apply_many({ "ColorColumn" }, { bg = options.transparent and "NONE" or colors.black })
  apply("Conceal", { bg = "darkgrey", fg = colors.beige_grey })
  apply("Cursor", { bg = colors.white, fg = colors.background })
  apply("Search", { bold = true, bg = colors.yellow, fg = colors.background })
  link({ "CurSearch", "Substitute", "QuickFixLine" }, "Search")
  apply("lCursor", { bg = colors.beige_grey, fg = colors.background })
  apply("CursorColumn", { bg = "grey40" })
  apply("CursorLine", { bg = colors.grey })
  apply("Directory", { fg = colors.light_green })
  apply("NonText", { fg = "#767676" })
  link({ "EndOfBuffer", "Whitespace", "CursorLineNr", "LineNr", "LineNrAbove", "LineNrBelow", "SpecialKey" }, "NonText")
  apply("TermCursor", { reverse = true })
  apply("ErrorMsg", { bg = colors.red, fg = colors.white })
  apply("VertSplit", { bg = "#121212", fg = "#444444" })
  link({ "WinSeparator" }, "VertSplit")
  apply("Folded", { bg = "#444444", fg = colors.white })
  apply("FoldColumn", { bg = colors.grey, fg = colors.cyan })
  link({ "CursorLineFold" }, "FoldColumn")
  apply("SignColumn", { fg = colors.white })
  link({ "CursorLineSign" }, "SignColumn")
  apply("IncSearch", { reverse = true })
  apply("MatchParen", { bg = "#005f5f", fg = colors.white })
  apply("ModeMsg", { bold = true })
  apply("StatusLine", { bg = background, fg = "#e4e4e4" })
  link({ "MsgSeparator", "StatusLineNC" }, "StatusLine")
  apply("MoreMsg", { bold = true, fg = colors.light_green })
  apply("Normal", { bg = background, fg = colors.beige_grey })
  link({ "NormalFloat" }, "Normal")
  if options.dim_inactive then
    apply("NormalNC", { bg = background, fg = colors.light_brown })
  else
    link({ "NormalNC" }, "Normal")
  end
  apply("FloatTitle", { bold = true, fg = colors.beige_grey })
  apply("Pmenu", { bg = "#444444", fg = colors.white })
  link({ "PmenuKind", "PmenuExtra" }, "Pmenu")
  apply("PmenuSel", { bg = colors.light_green, fg = colors.black })
  link({ "PmenuKindSel", "PmenuExtraSel" }, "PmenuSel")
  apply("PmenuSbar", { bg = "#5a647e" })
  apply("PmenuThumb", { bg = "#a8a8a8", fg = colors.white })
  apply("Question", { bold = true, fg = colors.light_green })
  apply("SpellBad", { undercurl = true, sp = colors.red })
  apply("SpellCap", { underline = true, sp = colors.blue, fg = colors.purple })
  apply("SpellLocal", { undercurl = true, sp = colors.cyan, fg = colors.cyan })
  apply("SpellRare", { underline = true, sp = colors.purple, fg = colors.pink })
  apply("TabLine", { bg = colors.grey, fg = colors.beige_grey })
  apply("TabLineFill", { bg = background })
  apply("TabLineSel", { bold = true, bg = colors.dark_green, fg = colors.beige_grey })
  apply("Title", { bold = true, fg = colors.white })
  apply("Visual", { bg = "#5A647E" })
  apply("WarningMsg", { fg = colors.dark_orange })
  apply("WildMenu", { bg = colors.yellow, fg = colors.black })
  apply("WinBar", { bold = true, bg = colors.dark_green, fg = colors.beige_grey })
  if options.dim_inactive then
    link({ "WinBarNC" }, "NormalNC")
  else
    link({ "WinBarNC" }, "TabLine")
  end

  apply("Comment", { fg = colors.light_brown })
  apply("Delimiter", { fg = colors.beige_grey })
  apply("Constant", { fg = colors.red })
  link({ "Character", "Identifier", "StorageClass", "Structure", "Type" }, "Constant")
  link({ "Typedef" }, "Type")
  apply("String", { fg = colors.light_green })
  apply("Number", { fg = colors.moss })
  link({ "Float" }, "Number")
  apply("Boolean", { fg = colors.blue })
  apply("Function", { fg = colors.light_orange })
  apply("Label", { fg = colors.purple })
  apply("Statement", { fg = colors.dark_orange })
  link({ "Conditional", "Repeat", "Operator", "Keyword", "Exception" }, "Statement")
  apply("PreProc", { fg = colors.dark_orange })
  link({ "Include", "Define", "Macro", "PreCondit" }, "PreProc")
  apply("Special", { fg = colors.light_green })
  link({ "SpecialChar", "Tag", "SpecialComment", "Debug" }, "Special")
  apply("Underlined", { underline = true, fg = "#80a0ff" })
  apply("Ignore", { fg = colors.background })
  apply("Error", { bg = "#990000", fg = colors.white })
  apply("Todo", { bold = true, fg = colors.red })

  apply("DiagnosticError", { fg = colors.red })
  apply("DiagnosticWarn", { fg = colors.dark_orange })
  apply("DiagnosticInfo", { fg = colors.blue })
  apply("DiagnosticHint", { fg = colors.beige_grey })
  apply("DiagnosticOk", { fg = colors.light_green })
  for _, severity in ipairs({ "Error", "Warn", "Info", "Hint", "Ok" }) do
    link({ "DiagnosticVirtualText" .. severity, "DiagnosticFloating" .. severity, "DiagnosticSign" .. severity }, "Diagnostic" .. severity)
  end
  apply("DiagnosticUnderlineError", { underline = true, sp = colors.red })
  apply("DiagnosticUnderlineWarn", { underline = true, sp = colors.dark_orange })
  apply("DiagnosticUnderlineInfo", { underline = true, sp = colors.blue })
  apply("DiagnosticUnderlineHint", { underline = true, sp = colors.beige_grey })
  apply("DiagnosticUnderlineOk", { underline = true, sp = colors.light_green })
  apply("DiagnosticDeprecated", { strikethrough = true, sp = colors.red })
  link({ "DiagnosticUnnecessary" }, "Comment")

  link({ "NvimInvalidSpacing" }, "ErrorMsg")
  link({ "NvimSpacing" }, "Normal")
  apply("FloatShadow", { bg = colors.black, blend = 80 })
  apply("FloatShadowThrough", { bg = colors.black, blend = 100 })
  apply("RedrawDebugNormal", { reverse = true })
  apply("RedrawDebugClear", { bg = "yellow" })
  apply("RedrawDebugComposed", { bg = "green" })
  apply("RedrawDebugRecompose", { bg = "red" })
  link({ "NvimInvalid" }, "Error")
  link({ "NvimString" }, "String")
  link({ "NvimNumber" }, "Number")
  link({ "NvimIdentifier" }, "Identifier")
  link({ "NvimNumberPrefix", "NvimOptionSigil" }, "Type")
  apply("NvimInternalError", { bg = colors.red, fg = colors.red })
  link({ "NvimFigureBrace", "NvimSingleQuotedUnknownEscape", "NvimInvalidSingleQuotedUnknownEscape" }, "NvimInternalError")
  apply_many({ "User1", "User6", "User7", "User8", "User9" }, { bold = true, bg = "#606060", fg = "#eeeeee" })
  apply("User2", { bold = true, bg = "#606060", fg = "#ffaf00" })
  apply("User3", { bold = true, bg = "#606060", fg = "#5fff00" })
  apply("User4", { bold = true, bg = "#606060", fg = "#870000" })
  apply("User5", { bold = true, bg = "#606060", fg = "#e4e4e4" })
  apply_many({ "diffNewFile", "diffFile" }, { bold = true, fg = colors.white })
  apply("pythonExceptions", { fg = "#ffaf87" })
  apply("pythonDoctest", { fg = "#8787ff" })
  apply("pythonDoctestValue", { fg = "#87d7af" })
  apply("mailEmail", { italic = true, fg = colors.light_green })
  apply("mailHeaderKey", { fg = "#ffdf5f" })
  link({ "mailSubject" }, "mailHeaderKey")
  apply_many({ "xmlTag", "xmlTagName", "xmlEndTag" }, { fg = "#dfaf5f" })
  link({ "htmlTag" }, "xmlTag")
  link({ "htmlTagName" }, "xmlTagName")
  link({ "htmlEndTag" }, "xmlEndTag")
  apply("checkbox", { fg = "#3a3a3a" })
  apply("checkboxDone", { bold = true, fg = "#5fff00" })
  apply("checkboxNotDone", { bold = true, fg = "#005fdf" })

  apply("DiffAdd", { fg = colors.light_green })
  apply("DiffChange", { fg = colors.cyan })
  apply("DiffDelete", { bold = true, fg = colors.red })
  apply("DiffText", { bold = true, bg = colors.red, fg = colors.white })
  link({ "diffAdded" }, "DiffAdd")
  link({ "diffRemoved" }, "DiffDelete")
  link({ "MiniDiffSignAdd", "MiniDiffOverAdd" }, "DiffAdd")
  link({ "MiniDiffSignDelete", "MiniDiffOverDelete" }, "DiffDelete")
  link({ "MiniDiffSignChange", "MiniDiffOverChange" }, "DiffChange")
  apply("MiniDiffOverContext", { bg = colors.purple })
  apply("IndentLine", { fg = "#767676" })
  apply("IndentBlanklineSpaceChar", { nocombine = true, fg = "#767676" })
  apply("IndentBlanklineContextStart", { underline = true, sp = colors.dark_brown })
  link({ "IndentBlanklineSpaceCharBlankline", "IndentBlanklineChar" }, "IndentBlanklineSpaceChar")
  apply("IndentBlanklineContextChar", { nocombine = true, fg = colors.dark_brown })
  apply("TelescopeBorder", { fg = colors.light_brown })
  apply("TelescopeSelection", { fg = colors.dark_orange })
  apply("TelescopeTitle", { fg = colors.red })
  link({ "TelescopePromptTitle" }, "TelescopeTitle")
  apply("TelescopePromptNormal", { fg = colors.yellow })
  link({ "TelescopePromptPrefix", "TelescopeMatching" }, "TelescopePromptNormal")
  link({ "zshDeref" }, "Constant")

  -- Completion
  link({ "CmpItemAbbr", "BlinkCmpLabel" }, "Normal")
  link({ "CmpItemAbbrDeprecated", "BlinkCmpLabelDeprecated" }, "Comment")
  apply_many({ "CmpItemAbbrMatch", "CmpItemAbbrMatchFuzzy", "BlinkCmpLabelMatch" }, { bold = true, fg = colors.yellow })
  link({ "CmpItemKind", "BlinkCmpKind" }, "Function")
  link({ "CmpItemMenu", "BlinkCmpSource" }, "Comment")
  link({ "BlinkCmpMenu", "BlinkCmpDoc", "BlinkCmpSignatureHelp" }, "NormalFloat")
  link({ "BlinkCmpMenuBorder", "BlinkCmpDocBorder", "BlinkCmpSignatureHelpBorder" }, "TelescopeBorder")
  link({ "BlinkCmpMenuSelection" }, "PmenuSel")
  link({ "BlinkCmpDocSeparator" }, "WinSeparator")
  link({ "BlinkCmpSignatureHelpActiveParameter" }, "Search")

  -- Git and file explorers
  link({ "GitSignsAdd", "GitSignsAddNr", "GitSignsAddLn" }, "DiffAdd")
  link({ "GitSignsChange", "GitSignsChangeNr", "GitSignsChangeLn" }, "DiffChange")
  link({ "GitSignsDelete", "GitSignsDeleteNr", "GitSignsDeleteLn" }, "DiffDelete")
  link({ "NeoTreeNormal", "NeoTreeNormalNC", "OilNormal" }, "Normal")
  link({ "NeoTreeDirectoryName", "NeoTreeDirectoryIcon", "OilDir", "OilDirIcon" }, "Directory")
  link({ "NeoTreeRootName" }, "Title")
  link({ "NeoTreeGitAdded" }, "DiffAdd")
  link({ "NeoTreeGitModified" }, "DiffChange")
  link({ "NeoTreeGitDeleted" }, "DiffDelete")
  link({ "OilLink" }, "Underlined")
  link({ "OilCopy", "OilMove", "OilCreate" }, "DiffAdd")
  link({ "OilDelete" }, "DiffDelete")
  link({ "OilPermission", "OilSize", "OilMTime" }, "Comment")

  -- UI plugins
  link({ "WhichKey", "WhichKeyGroup" }, "Function")
  link({ "WhichKeyDesc" }, "Normal")
  link({ "WhichKeySeparator", "WhichKeyValue" }, "Comment")
  link({ "WhichKeyFloat" }, "NormalFloat")
  link({ "WhichKeyBorder" }, "TelescopeBorder")
  link({ "LazyNormal" }, "NormalFloat")
  link({ "LazyButton" }, "Pmenu")
  link({ "LazyButtonActive" }, "PmenuSel")
  link({ "LazyH1" }, "Title")
  link({ "LazyComment" }, "Comment")
  link({ "LazyReasonPlugin" }, "Function")
  link({ "LazyValue" }, "String")
  link({ "NoiceCmdline", "NoicePopup", "NoiceConfirm" }, "NormalFloat")
  link({ "NoiceCmdlinePopup", "NoicePopupmenu" }, "Pmenu")
  link({ "NoiceCmdlinePopupBorder", "NoicePopupBorder", "NoiceConfirmBorder" }, "TelescopeBorder")
  link({ "NoiceCmdlineIcon", "NoiceFormatEvent", "NoiceFormatKind" }, "Special")
  link({ "NoiceFormatTitle" }, "Title")
  link({ "NoiceFormatDate" }, "Comment")
  link({ "NoiceFormatProgressDone" }, "DiffAdd")
  link({ "NoiceFormatProgressTodo" }, "Comment")

  -- Indentation and rendered Markdown
  apply("IblIndent", { fg = "#767676" })
  link({ "IblWhitespace" }, "IblIndent")
  apply("IblScope", { fg = colors.dark_brown })
  link({ "IblScopeChar" }, "IblScope")
  apply_many({ "RenderMarkdownH1", "RenderMarkdownH2", "RenderMarkdownH3", "RenderMarkdownH4", "RenderMarkdownH5", "RenderMarkdownH6" }, { bold = true, fg = colors.white })
  link({ "RenderMarkdownCode", "RenderMarkdownCodeInline" }, "Pmenu")
  link({ "RenderMarkdownBullet", "RenderMarkdownDash" }, "Special")
  link({ "RenderMarkdownQuote" }, "Comment")
  link({ "RenderMarkdownTableHead" }, "Title")
  link({ "RenderMarkdownTableRow" }, "Normal")
  link({ "RenderMarkdownLink" }, "Underlined")

  apply("@text", { fg = colors.beige_grey })
  link({ "@text.title", "@markup.heading" }, "Title")
  link({ "@text.todo", "@markup.todo" }, "Todo")
  link({ "@markup" }, "@text")
  link({ "@number", "@float" }, "Number")
  link({ "@conceal" }, "NonText")
  apply("@function.call", { fg = colors.beige_grey })
  link({ "@parameter", "@variable.parameter", "@punctuation.bracket", "@punctuation.delimiter", "@field", "@variable", "@operator" }, "@function.call")
  apply("@label", { fg = colors.purple })
  link({ "@variable.member" }, "@label")
  link({ "@property", "@namespace", "@text.reference", "@constant", "@type", "@character", "@type.definition", "@storageclass" }, "Identifier")
  link({ "@module", "@module.builtin", "@tag.attribute" }, "Identifier")
  link({ "@comment", "@structure", "@text.literal" }, "Comment")
  link({ "@preproc", "@attribute", "@function.builtin", "@function.macro", "@include", "@constant.macro", "@define", "@macro", "@type.qualifier" }, "PreProc")
  link({ "@function.method", "@tag", "@function", "@method" }, "Function")
  link({ "@conditional", "@exception", "@keyword", "@keyword.conditional", "@keyword.directive", "@keyword.exception", "@keyword.function", "@keyword.import", "@keyword.repeat", "@keyword.return", "@keyword.type", "@repeat" }, "Keyword")
  link({ "@constructor", "@character.special", "@punctuation", "@debug" }, "Special")
  link({ "@string", "@string.escape", "@string.regex", "@string.special", "@string.special.path" }, "String")
  link({ "@string.special.url", "@text.uri", "@text.underline" }, "Underlined")
  link({ "@markup.link" }, "Underlined")
  link({ "@markup.raw" }, "String")
  link({ "@markup.quote" }, "Comment")
  link({ "@markup.list" }, "Special")
  link({ "@markup.math" }, "Number")
  apply("@label.json", { fg = colors.light_green })
  apply("@constant.builtin", { fg = colors.blue })
  link({ "@variable.builtin", "@boolean" }, "@constant.builtin")
  link({ "@text.diff.add" }, "diffAdded")
  link({ "@text.diff.delete" }, "diffRemoved")
  link({ "@diff.plus" }, "DiffAdd")
  link({ "@diff.delta" }, "DiffChange")
  link({ "@diff.minus" }, "DiffDelete")
  link({ "@lsp.type.type", "@lsp.type.builtinType", "@lsp.type.class", "@lsp.type.enum", "@lsp.type.interface", "@lsp.type.struct", "@lsp.type.typeParameter" }, "Type")
  link({ "@lsp.type.comment" }, "Comment")
  link({ "@lsp.type.enumMember" }, "Constant")
  link({ "@lsp.type.decorator", "@lsp.type.macro" }, "PreProc")
  link({ "@lsp.type.event" }, "Label")
  link({ "@lsp.type.keyword" }, "Keyword")
  link({ "@lsp.type.number" }, "Number")
  link({ "@lsp.type.boolean" }, "Boolean")
  link({ "@lsp.type.regexp", "@lsp.type.string" }, "String")
  link({ "@lsp.type.operator" }, "Operator")
  link({ "@lsp.type.namespace", "@lsp.type.property" }, "Identifier")
  link({ "@lsp.type.parameter", "@lsp.type.variable" }, "@function.call")
  link({ "@lsp.type.function", "@lsp.type.method" }, "Function")
  link({ "@operator.ruby" }, "PreProc")
  apply("@symbol.ruby", { fg = colors.cyan })
  link({ "@string.special.symbol" }, "@symbol.ruby")
  link({ "@tag.delimiter.html" }, "PreProc")
  link({ "@property.typescript" }, "@text")
  link({ "@field.yaml" }, "Function")
  link({ "@punctuation.special.yaml" }, "PreProc")
end

return M
