background = #2B2B2B
foreground = #E6E1DC
cursor-color = #CC7833
selection-background = #87AF5F
selection-foreground = #2B2B2B
palette = 0=#2B2B2B
palette = 1=#DA4939
palette = 2=#FFC66D
palette = 3=#A5C261
palette = 4=#6D9CBE
palette = 5=#D0D0FF
palette = 6=#87AF5F
palette = 7=#F3F4F5
palette = 8=#5F5F87
palette = 9=#CC7833
palette = 10=#A5C261
palette = 11=#FFC66D
palette = 12=#6D9CBE
palette = 13=#D0D0FF
palette = 14=#87AF5F
palette = 15=#F3F4F5
